FROM docker.io/bitnami/airflow:2
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         default-jdk \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER 1001

# docker build -t airflow-worker-java:2 -f Dockerfile-airflow-worker .